Banish class_eval
winnipegrb/just_chew pull request #23
Opened 2017-09-16 22:30 UTC by thetamind

The first two commits banish `class_eval` in return for `Module#prepend`.

The last two commits switch to existing extension points in Clearance and RSpec.

2017-09-16 22:56 UTC, gmcgibbon requested changes
See comments.

2017-09-16 22:56 UTC, gmcgibbon commented on config/routes.rb
> +  get '/sign_up' => 'clearance/users#new', as: 'sign_up'
Please use the `to:` key instead of `=>` syntax to map controllers to routes. I think it is much clearer.

2017-09-16 22:56 UTC, gmcgibbon commented on spec/support/helpers/json_response_helper.rb
> +  config.include_context 'JSON response', type: :controller
While this is a cleaner solution, I much prefer directly interacting with `response.json` rather than knowing to use `json_response`. Please revert this change. You may make the monkey patch cleaner by defining a module and including or prepending the module to `ActionDispatch::TestResponse`.

2017-09-16 22:56 UTC, gmcgibbon commented on config/routes.rb
> +  resources :passwords, controller: 'clearance/passwords', only: %i(create new)
I wanted to avoid defining each route like this since I was only making small changes to Clearance's internals. However, as we develop the app further this will be a better approach so thanks for doing this!

2017-09-16 23:52 UTC, thetamind commented on config/routes.rb
> +  resources :passwords, controller: 'clearance/passwords', only: %i(create new)
Ah, I understand your reasoning to make a minimal change.

The explicit, large blob of routes does make me want to corral it with `########` comments or something...

2017-09-16 23:54 UTC, thetamind commented on config/routes.rb
> +  get '/sign_up' => 'clearance/users#new', as: 'sign_up'
Changed: 0064080

2017-09-16 23:57 UTC, thetamind commented on spec/support/helpers/json_response_helper.rb
> +  config.include_context 'JSON response', type: :controller
Changed: 7102252

2017-09-17 01:21 UTC, gmcgibbon approved these changes

2017-09-17 01:22 UTC, merged